name: Spellcheck
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@fcc5ca8351f0590978f238d6babfe3f28afc361f # 0.65.0
        with:
          config_path: .github/spellcheck-settings.yml
          task_name: Markdown
