name: Spellcheck
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@390a08ee9c46943112f21d2ff671649a2bacd33f # 0.62.0
        with:
          config_path: .github/spellcheck-settings.yml
          task_name: Markdown
